# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteCierre',
            fields=[
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lotes.Lote')),
                ('fecha', models.DateField()),
                ('cobrado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gasto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'ordering': ('lote',),
            },
        ),
        migrations.CreateModel(
            name='LoteRevisado',
            fields=[
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lotes.Lote')),
                ('fecha', models.DateField()),
            ],
            options={
                'ordering': ('lote',),
            },
        ),
        migrations.RemoveField(
            model_name='lote',
            name='cierre',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='cobrado',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='gasto',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='revisado',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='total',
        ),
    ]
