# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimientos', '0001_initial'),
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='PagoGasto',
            fields=[
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pagos.Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.Gasto')),
            ],
        ),
        migrations.CreateModel(
            name='PagoMantenimiento',
            fields=[
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pagos.Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientos.Mantenimiento')),
            ],
        ),
    ]
