# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_auto_20160517_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
