# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'ordering': ('periodo',),
            },
        ),
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ('grupo', 'nombre')},
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='total',
        ),
        migrations.AddField(
            model_name='mantenimientoperiodo',
            name='mantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimientos.Mantenimiento'),
        ),
    ]
