# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0004_auto_20160601_1604'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mantenimientoperiodo',
            unique_together=set([('mantenimiento', 'periodo')]),
        ),
    ]
