# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=255)),
                ('fecha_cobranza', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='CobranzaCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('cierre', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cobranza',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranzas.CobranzaCuenta'),
        ),
    ]
