# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobranzaLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255, unique=True)),
                ('inicio', models.DateField()),
                ('cierre', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cobranza',
            name='cuenta',
        ),
        migrations.DeleteModel(
            name='CobranzaCuenta',
        ),
        migrations.AddField(
            model_name='cobranza',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranzas.CobranzaLote'),
        ),
    ]
