# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0002_auto_20160428_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranza',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranzas.CobranzaLote'),
        ),
    ]
