# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranzas', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255, unique=True)),
                ('inicio', models.DateField()),
                ('cierre', models.DateField(blank=True, null=True)),
                ('cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('gasto', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('revisado', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('numero',),
            },
        ),
        migrations.CreateModel(
            name='LoteCobranza',
            fields=[
                ('cobranza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cobranzas.Cobranza')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.Lote')),
            ],
        ),
        migrations.CreateModel(
            name='LotePago',
            fields=[
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pagos.Pago')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.Lote')),
            ],
        ),
    ]
