# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CajaLote',
            fields=[
                ('caja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cajas.Caja')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.Lote')),
            ],
        ),
        migrations.CreateModel(
            name='CajaPago',
            fields=[
                ('caja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cajas.Caja')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.Pago')),
            ],
        ),
    ]
