# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vigencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='deuda',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='vigente',
        ),
        migrations.AddField(
            model_name='contrato',
            name='cobro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.Cobro'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='vigencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.Vigencia'),
        ),
    ]
