# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_auto_20160428_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobro',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='vigencia',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cobro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contratos.Cobro'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vigencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contratos.Vigencia'),
        ),
    ]
