# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_pago_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.CharField(max_length=255),
        ),
    ]
