# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_pago_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.PagoTipo'),
        ),
        migrations.AlterField(
            model_name='pagotipo',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
